<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cev</string>
	</array>
	<key>name</key>
	<string>Ceveral</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storagetypes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enum</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#message</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#packaging</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#service</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#annotation</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.ceveral</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>annotation</key>
		<dict>
			<key>begin</key>
			<string>(@)([a-zA-Z][a-zA-Z0-9_]*)+\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.decorator.ceveral</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ceveral</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#json_value</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.ceveral</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.ceveral</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.ceveral</string>
		</dict>
		<key>enum</key>
		<dict>
			<key>begin</key>
			<string>(enum)(\s+)([A-Za-z][A-Za-z0-9_]*)(\s*)(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ceveral</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.ceveral</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(to|extensions)\b</string>
					<key>name</key>
					<string>keyword.source.ceveral</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.ceveral</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.type.annotation.ceveral</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ceveral</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Za-z][A-Za-z0-9_]+)(\s*)((=)(\s*)([0-9]*))?;</string>
				</dict>
			</array>
		</dict>
		<key>json_array</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#json_value</string>
				</dict>
			</array>
		</dict>
		<key>json_value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#json_array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ceveral</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([0-9]+)</string>
				</dict>
			</array>
		</dict>
		<key>message</key>
		<dict>
			<key>begin</key>
			<string>(record)(\s+)([A-Za-z][A-Za-z0-9_.]*)(\s*)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ceveral</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.message.ceveral</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#annotation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>([A-Za-z][A-Za-z0-9_]*)(\s*)(:)(\s*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.object.ceveraltype.ceveral</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.type.annotation.ceveral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.ceveral</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([A-Za-z][A-Za-z0-9_]*)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#storagetypes</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.source.ceveral</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.name.class.ceveral</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(map)&lt;([A-Za-z][A-Za-z0-9_]*),\s*([A-Za-z][A-Za-z0-9_]*)&gt;\s+([A-Za-z][A-Za-z0-9_]*)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\[)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.brace.square.ceveral</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\])</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.brace.square.ceveral</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#storagetypes</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.name.type.ceveral</string>
										</dict>
									</dict>
									<key>match</key>
									<string>([A-Za-z][A-Za-z0-9_]*)</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>packaging</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ceveral</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(import)(?=(\s+)(["]?[./A-Za-z][A-Za-z0-9-_./]*["]?)(;))</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ceveral</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(package)(?=(\s+)(["]?[A-Za-z][A-Za-z0-9-_./]*["]?)(;))</string>
				</dict>
			</array>
		</dict>
		<key>service</key>
		<dict>
			<key>begin</key>
			<string>(service)(\s+)([A-Za-z][A-Za-z0-9_.]*)(\s*)(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ceveral</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.message.ceveral</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(rpc)\s+([A-Za-z][A-Z-a-z0-9_]+)\s*\((stream\s+)?([A-Za-z0-9_]+)\)\s+(returns)\s+\((stream\s+)?([A-Za-z0-9_]+)\)\{?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.source.ceveral</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.source.ceveral</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.source.ceveral</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.source.ceveral</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}|;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#option</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>storagetypes</key>
		<dict>
			<key>match</key>
			<string>\b(double|float|int32|int64|uint32|uint64|int16|uint16|int8|uint8|boolean|string|bytes|date)\b</string>
			<key>name</key>
			<string>support.type.primitive.ceveral</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ceveral</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ceveral</string>
	<key>uuid</key>
	<string>750ac1f3-b172-48de-b1a4-a3c310c4a293</string>
</dict>
</plist>
